# Generated by Django 5.2.7 on 2025-10-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='receitas/images/', verbose_name='Imagem')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('política', 'Política'), ('esportes', 'Esportes'), ('entretenimento', 'Entretenimento'), ('tecnologia', 'Tecnologia'), ('saúde', 'Saúde'), ('economia', 'Economia'), ('outros', 'Outros')], default='Outros', max_length=50, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('introducao', models.TextField(verbose_name='Introdução')),
                ('desenvolvimento_inicial', models.TextField(verbose_name='Desenvolvimento')),
                ('video', models.TextField(help_text='link do youtube', verbose_name='Vídeo')),
                ('desenvolvimento_final', models.TextField(verbose_name='Desenvolvimento')),
                ('conclusao', models.TextField(verbose_name='Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-created_at'],
            },
        ),
    ]
