# Generated by Django 5.2.7 on 2025-11-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizacao',
            name='data',
        ),
        migrations.AddField(
            model_name='visualizacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
