# Generated by Django 5.2.7 on 2025-10-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video',
            field=models.TextField(blank=True, help_text='link do youtube', verbose_name='Vídeo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='noticias.categoria', verbose_name='Categoria'),
        ),
    ]
