# Generated by Django 5.2.7 on 2025-11-20 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_visualizacao_data_visualizacao_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='noticias.perfil', verbose_name='Perfil'),
        ),
    ]
