# Generated by Django 5.2.7 on 2025-11-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_video_visualizacao_curtida'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bairro',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
