# Generated by Django 5.2.7 on 2025-10-09 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_bairro_perfil_noticia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='noticias.bairro', verbose_name='Bairro'),
        ),
    ]
