# Generated by Django 5.2.7 on 2025-10-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('noticias', '0005_alter_noticia_usuario_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email_usuario', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nome_usuario', models.CharField(max_length=150, verbose_name='Nome de Usuário')),
                ('senha_usuario', models.CharField(max_length=128, verbose_name='Senha')),
                ('perfil', models.CharField(choices=[('usuario', 'Usuário Comum'), ('editor', 'Editor')], default='usuario', max_length=10, verbose_name='Perfil')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
